name: DynamicShop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0 #https://github.com/actions/checkout/releases
    - run: sed "s/{BUILDID}/$GITHUB_RUN_NUMBER/g" pom.xml > _pom.xml; rm pom.xml; mv _pom.xml pom.xml
    - name: Set up JDK 8
      uses: actions/setup-java@v3.9.0 #https://github.com/actions/setup-java/releases
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Build with Maven
      run: mvn clean install
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3.1.2 #https://github.com/actions/upload-artifact/releases
      with:
        name: Package
        path: staging
